# -*- coding: utf-8 -*-
"""Amazon_Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0xi8feW8nami4jcdTLUjpjsT92Ea5d2
"""

!pip install transformers datasets scikit-learn -q

"""## 1. 上傳資料"""

from google.colab import drive
drive.mount('/content/drive')

FILE_PATH = '/content/drive/MyDrive/Colab Notebooks/Amazon_Reviews/Amazon_Reviews.csv'

import pandas as pd
df = pd.read_csv(FILE_PATH, on_bad_lines='skip', engine='python')
print(f'載入成功，共 {len(df)} 筆')

"""## 2. 前處理"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

df = pd.read_csv(FILE_PATH, on_bad_lines='skip', engine='python')
print(f'原始筆數: {len(df)}')

def parse_rating(r):
    m = re.search(r'(\d)', str(r))
    return int(m.group(1)) if m else None

df['label'] = df['Rating'].apply(parse_rating)
df = df.dropna(subset=['label', 'Review Text'])
df['label'] = df['label'].astype(int)

def clean_text(t):
    return re.sub(r'\s+', ' ', str(t).strip())

df['text_clean']  = df['Review Text'].apply(clean_text)
df['title_clean'] = df['Review Title'].fillna('').apply(clean_text)

print(f'清理後筆數: {len(df)}')
print(f'\n評分分佈:')
print(df['label'].value_counts().sort_index())

# 80% train / 20% val
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])

print(f'Train: {len(train_df)} | Val: {len(val_df)}')

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.array([1,2,3,4,5]),
    y=train_df['label'].values
)
print(f'\nClass weights: { {i+1: round(w,2) for i, w in enumerate(class_weights)} }')

"""## 3. Dataset & DataLoader"""

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'使用裝置: {device}')
if device.type == 'cuda':
    print(f'GPU: {torch.cuda.get_device_name(0)}')

MODEL_NAME = 'roberta-base'
tokenizer  = AutoTokenizer.from_pretrained(MODEL_NAME)

MAX_LEN    = 256
BATCH_SIZE = 16

class ReviewDataset(Dataset):
    def __init__(self, df, tokenizer, max_len=MAX_LEN):
        self.titles  = df['title_clean'].tolist()
        self.texts   = df['text_clean'].tolist()
        self.labels  = (df['label'].values - 1).tolist()  # 0-indexed
        self.tok     = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        enc = self.tok(
            self.titles[idx],
            self.texts[idx],
            max_length=self.max_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )
        return {
            'input_ids':      enc['input_ids'].squeeze(),
            'attention_mask': enc['attention_mask'].squeeze(),
            'label':          torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_dataset = ReviewDataset(train_df, tokenizer)
val_dataset   = ReviewDataset(val_df,   tokenizer)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print(f'Train batches: {len(train_loader)} | Val batches: {len(val_loader)}')

"""## 4. 建立模型"""

from transformers import AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW

NUM_EPOCHS = 3
LR         = 2e-5

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=5
).to(device)

# weight_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)
# loss_fn = torch.nn.CrossEntropyLoss(weight=weight_tensor)
loss_fn = torch.nn.CrossEntropyLoss()

optimizer   = AdamW(model.parameters(), lr=LR, weight_decay=0.01)
total_steps = len(train_loader) * NUM_EPOCHS
scheduler   = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(total_steps * 0.2),
    num_training_steps=total_steps
)

total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'訓練參數量: {total_params:,}')

"""## 5. 訓練"""

def evaluate(model, loader):
    model.eval()
    all_preds, all_labels = [], []
    total_loss = 0.0
    with torch.no_grad():
        for batch in loader:
            input_ids      = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels         = batch['label'].to(device)
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            total_loss += loss_fn(outputs.logits, labels).item()
            preds = outputs.logits.argmax(dim=-1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    acc = accuracy_score(all_labels, all_preds)
    return acc, total_loss / len(loader), all_preds, all_labels


history = {'train_acc': [], 'val_acc': [], 'train_loss': [], 'val_loss': []}
best_val_acc = 0.0

for epoch in range(NUM_EPOCHS):
    model.train()
    total_loss = 0.0
    correct = total = 0

    for step, batch in enumerate(train_loader):
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels         = batch['label'].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss    = loss_fn(outputs.logits, labels)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()
        preds    = outputs.logits.argmax(dim=-1)
        correct += (preds == labels).sum().item()
        total   += labels.size(0)

        if (step + 1) % 100 == 0:
            print(f'  Epoch {epoch+1} | Step {step+1}/{len(train_loader)} '
                  f'| Loss: {loss.item():.4f} | Acc: {correct/total:.4f}')

    train_acc  = correct / total
    train_loss = total_loss / len(train_loader)
    val_acc, val_loss, _, _ = evaluate(model, val_loader)

    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)

    print(f'\nEpoch {epoch+1}/{NUM_EPOCHS} '
          f'| Train Acc: {train_acc:.4f} Loss: {train_loss:.4f} '
          f'| Val Acc: {val_acc:.4f} Loss: {val_loss:.4f}')

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), 'best_bert_model.pt')
        print(f'  >>> 儲存最佳模型 (val_acc={val_acc:.4f})')

    print()

import shutil
shutil.copy('best_bert_model.pt', '/content/drive/MyDrive/Colab Notebooks/Amazon_Reviews/best_bert_model.pt')
print('已儲存到 Google Drive')

"""## 6. 評估結果"""

# 載入最佳權重，在 val set 上評估
model.load_state_dict(torch.load('best_bert_model.pt'))
val_acc, _, val_preds, val_labels = evaluate(model, val_loader)

# 轉回 1-indexed
val_preds_1  = [p + 1 for p in val_preds]
val_labels_1 = [l + 1 for l in val_labels]

print(f'Val Accuracy: {val_acc:.4f}\n')
print(classification_report(
    val_labels_1, val_preds_1,
    target_names=['1★','2★','3★','4★','5★']
))

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Confusion Matrix
cm = confusion_matrix(val_labels_1, val_preds_1)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['1★','2★','3★','4★','5★'],
            yticklabels=['1★','2★','3★','4★','5★'])
axes[0].set_title(f'Confusion Matrix\n(Val Acc = {val_acc:.4f})')
axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('Actual')

# Accuracy 曲線
epochs = range(1, NUM_EPOCHS + 1)
axes[1].plot(epochs, history['train_acc'], marker='o', label='Train')
axes[1].plot(epochs, history['val_acc'],   marker='s', label='Val')
axes[1].set_title('Accuracy 曲線')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Accuracy')
axes[1].set_xticks(epochs); axes[1].legend()

# Loss 曲線
axes[2].plot(epochs, history['train_loss'], marker='o', label='Train')
axes[2].plot(epochs, history['val_loss'],   marker='s', label='Val')
axes[2].set_title('Loss 曲線')
axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('Loss')
axes[2].set_xticks(epochs); axes[2].legend()

plt.tight_layout(); plt.show()